### ISSUE TITLE
Negative temperatures not supported

### ISSUE THREAD

**Issue by iarbre** [sholzmayer/homebridge-openweathermap-temperature#1]
Hi,

thanks for the plugin. It works great. At least in summer. 😉  If temperatures fall below zero degree, they arent transmitted anymore. This can be fixed by adding:
```
.setProps( {minValue: -100} )
```
in line 77 of index.js.

Hope it helps,
Torsten

**Comment by sholzmayer** [comment]
Thanks for this report. This explains why it doesn't work in the last days... I'll fix it.
