### ISSUE TITLE
Openweather-map Sensor

### ISSUE THREAD

**Issue by helde86** [sholzmayer/homebridge-openweathermap-temperature#2]
I can see the temperature on my "Home".
But it's not a sensor. It's just an Info.
I can't use it to automation.
Can I customize the config to use it for that?

**Comment by sholzmayer** [comment]
I didn't implement a way to do so yet, but you could feel free to contribute and implement this by your own. I would accept pull requests for new features and improvements ¯\(ツ)/¯

**Comment by mobster1940** [comment]
I also wanted to create a trigger based on the current outside temperature, but unfortunately I discovered that the Home app doesn't allow data ranges as triggers (yet?), so there is no way to do that from there. On the good side, the Eve app does allow triggers based on data ranges, so you can create the scene that you want there and use it in the Home app. Hope I helped!
